### ISSUE TITLE
Plans to update to 0.5.2?

### ISSUE THREAD

**Issue by omphalosskeptic** [openshift-quickstart/openshift-ghost-quickstart#28]
Is this quickstart going to be updated to the current version of ghost (in the near future)?

**Comment by brettof86** [comment]
I created a bash script to upgrade mine. I created a [gist](https://gist.github.com/brettof86/48895e95d8c68148ae74) if anyone is interested. Should we add it to the project for users? I can create a PR if you're interested @fuzzmz.

**Comment by fuzzmz** [comment]
@Brett, sure, go ahead.


-- Serban Constantin

**Comment by corey112358** [comment]
quickstart has been updated to 0.5.10
