### ISSUE TITLE
which Database is being used in ghost quickstart? 

### ISSUE THREAD

**Issue by vijayk036** [openshift-quickstart/openshift-ghost-quickstart#32]
Hi Guys,

I have installed ghost on open shift using quick start, also I copied the source code to my local machine, blog is working fine.
Now when I open my config file I could see different environments like "development","production","testing-mysql" etc. As I installed my app with --production command line argument I assume the app is running in a production environment i.e., using production setting in config file which is as below

production: {
url: 'http://'+process.env.OPENSHIFT_APP_DNS,
mail: {
transport: 'SMTP',
options: {
service: 'Mailgun',
auth: {
user: 'username',
pass: 'password'
}
}
},
database: {
client: 'sqlite3',
connection: {
filename: path.join(__dirname, '/content/data/ghost.db')
},
debug: false
},
server: {
// Host to be passed to node's net.Server#listen()
host: process.env.OPENSHIFT_NODEJS_IP,
// Port to be passed to node's net.Server#listen(), for iisnode set this to process.env.PORT
port: process.env.OPENSHIFT_NODEJS_PORT
}
},

So does this mean my app is using sqlite3 database and if so what would be the username and password of my database root user as I never set it up explicitly. And also what has to be done to change this to mysql database?
Thank you

**Comment by kerneldeveloper** [comment]
But now it seems this quickstart Ghost installation uses MySQL.

**Comment by developercorey** [comment]
This ghost quickstart can use either MySQL or PostgreSQL, as chosen during the installation.  SQLite is no longer supported.
