### ISSUE TITLE
how to update this git to new version?

### ISSUE THREAD

**Issue by tvvocold** [openshift-quickstart/openshift-ghost-quickstart#34]
https://github.com/TryGhost/Ghost/releases/tag/0.5.6

**Comment by tvvocold** [comment]
btw, how to do 301 in openshift' ghost?
i had google around and find http://codenimbus.com/2014/01/15/redirecting-www-domain-to-non-www-on-ghost/ but How to redirect non-www to www domain? Any advice?

**Comment by corey112358** [comment]
quickstart has been updated to 0.5.10
