### ISSUE TITLE
Upgrading to 5.10 required extra steps

### ISSUE THREAD

**Issue by cleversprocket** [openshift-quickstart/openshift-ghost-quickstart#42]
Following the steps in #28 isn't enough to upgrade to 0.5.10

**EDIT:** I was able to get this working locally but I see `error: javascript files have not been built` after pushing the commit and tailing the logs.

I was able to get it working by following the steps in #28 and also copying all the additional files in the root including removing the old Gruntfile.js and bower.json.
.bowerrc
.gitmodules
.jscsrc
.jshintrc
.npmignore
.travis.yml
bower.json
Gruntfile.js
npm-shrinkwrap.json

Run npm install.
Run grunt init (you'll need to have the grunt-cli installed).

I don't know if all the above files are necessary but I highly doubt having them causes any harm :)

**Comment by MunGell** [comment]
I believe Ghost developers start using npm-shrinkwrap feature since 0.5.9, so it might be required to have updated npm-shrinkwrap.json in your repository now.

**Comment by cleversprocket** [comment]
The above steps worked when running locally but failed on the server. I see 'error: javascript files have not been built after pushing the commit and tailing the logs.' 
Does grunt need to be run on the server?

**Comment by corey112358** [comment]
This quickstart has now been updated to 0.5.10
