### ISSUE TITLE
How to add new themes on ghost/openshift-quickstart?

### ISSUE THREAD

**Issue by camilodelvasto** [openshift-quickstart/openshift-ghost-quickstart#50]
Hi,

I installed ghost locally (not from the quickstart) and created a theme, which works fine on my local install. I tried cloning this theme (which for the moment is just a copy of casper with a different name and version) in the /content/themes folder from the repo openshift gave me. After pushing, I can see in my openshift ghost blog that the new theme is there, but the theme is broken.... so it displays only the name, not the version. and of course if I select it, it displays a 500 error on the front page:

Failed to lookup view "index" in views directory "/var/lib/openshift/559eec785004461bd30000e2/app-root/runtime/repo/content/themes/starticsghost"
![screenshot 2015-07-09 17 28 24](https://cloud.githubusercontent.com/assets/4598282/8608377/02912a48-2660-11e5-9b63-b6871fead771.png)

Am I missing something? How exactly should I proceed in order to upload new themes to my ghost blog there? Thanks for the help, it's driving me nuts!

**Comment by MunGell** [comment]
Hi @camilodelvasto 

Is there any way to share the theme you are trying to install with me?
It sounds like a file missing or theme configuration issue.

Thanks

**Comment by camilodelvasto** [comment]
HI @MunGell, thanks for your answer. Here you can see the theme I'm trying to install: https://github.com/camilodelvasto/starticsghost.git - just a clone from casper with an addition on css. The theme works locally.
I also tried to install another free theme that I found but got the same error, so I'm definitely missing something.... thanks!

**Comment by MunGell** [comment]
Thanks, I will take a look and come back to you

**Comment by MunGell** [comment]
Hey @camilodelvasto 

Your theme is working on my local machine as well, could you please copy all the files of your theme to repository's `content/themes` directory and try to redeploy your application?

It looks like you actually missing some files on the server (may be there was a merge conflict or you haven't committed all of them first time). Please, make sure that `index.hbs` is present in the repository that you are pushing to production. 

Let me know if redeployment didn't work.

**Comment by camilodelvasto** [comment]
Hey @MunGell 
I did that, actually just cloned my theme in the `content/themes` directory, pushed the changes and got the same... but after rhc-ing in the server I'm seeing the theme folder is empty. So, perhaps the folder gets removed during the deployment? Checked .gitignore and the themes are not there, so they should exist in the repo.... any clue? thanks for your help!

**Comment by camilodelvasto** [comment]
@MunGell it works now... I just had to remove the .git directory before pushing!

**Comment by MunGell** [comment]
Cool, you are welcome!
