### ISSUE TITLE
How to restart Ghost? 

### ISSUE THREAD

**Issue by tiborsaas** [openshift-quickstart/openshift-ghost-quickstart#58]
I've tried `service ghost restart` but probably it's not for RedHat. I'm a linux noob btw :) 

So all I want is to reload the app, because I want to change the domain in the config.js

Is the app running in:
`/app-root/runtime/repo` ?

**Comment by alejonext** [comment]
restart the app

**Comment by tiborsaas** [comment]
That's the question. I want to do it via command line.

**Comment by alejonext** [comment]
well... restart only the nodejs. Because, the "app" or "ghost" are in nodejs thread, and "restart" only the ghost in impossible

**Comment by tiborsaas** [comment]
I can't find a way to do that despite I'm a power searcher in Google. 

I can't even install `forever`, or `nodemon` throws errors. Probably it's because OpenShift is really limited :/

**Comment by MunGell** [comment]
You could restart your application in OpenShift admit panel: https://openshift.redhat.com/app/console

Or using command line tool (on your machine, not over SSH), check the documentation here: https://developers.openshift.com/en/managing-common-rhc-commands.html

**Comment by tiborsaas** [comment]
Thanks @MunGell, I was afraid of this, that's very slow unfortunately.
