### ISSUE TITLE
No images in my blog

### ISSUE THREAD

**Issue by Larraby** [openshift-quickstart/openshift-ghost-quickstart#61]
I've done everything written in manual, created an app, cloned it locally, added changes(with images), pushed them but no images appeared
Console says:
"Created persistent images directory"
"Symlinking images directory"

Can you tell me please what else should I do to get images on server?

**Comment by Larraby** [comment]
Uploaded them by sftp to data directory by myself

**Comment by heartnn** [comment]
It seems .openshift folder will work.
